# Generated by Django 3.0.14 on 2024-05-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание')),
                ('count', models.IntegerField(verbose_name='Число')),
            ],
            options={
                'verbose_name': 'Новая модель',
                'verbose_name_plural': 'Новые модели',
            },
        ),
    ]
